# Generated by Django 4.1 on 2023-08-11 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uname", models.CharField(max_length=250)),
                ("pwd", models.CharField(max_length=250)),
                ("cpwd", models.CharField(max_length=250)),
            ],
        ),
    ]
